"""add_raw_text_to_resumes

Revision ID: 1bc5dfd58aea
Revises: 7fe3cf7bb9f3
Create Date: 2026-06-18 19:53:16.304459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc5dfd58aea'
down_revision: Union[str, None] = '7fe3cf7bb9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
