"""add_parsed_content_to_resumes

Revision ID: b308aff3641d
Revises: 1bc5dfd58aea
Create Date: 2026-06-18 21:28:51.062154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b308aff3641d'
down_revision: Union[str, None] = '1bc5dfd58aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_content')
    # ### end Alembic commands ###
